### ISSUE TITLE
更新したいこと

### ISSUE THREAD

**Issue by Sorakime** [Sorakime/Utilythes#3]
# 修正
- [x] ライトモードへの全対応
- [x] Locker(*1)を引っ張る時のアニメーションをもっと軽く
- [x] Locker(*1)およびDockのブラーの演出

書きたいことだけ書きます。

## LockerおよびDockのブラーの演出
今現在、
```css
dock-bar::before{
  content: '';
  display: block;
  position: absolute;
  top: 0; left: -400px;
  background: var(--background);
  background-clip: content-box;
  background-position: bottom center;
  background-size: cover;
  background-repeat: no-repeat;
  width: calc(100% + 400px); height: 110%;
  padding: 0;
  z-index: -1;
  filter: blur(30px) brightness(90%);
}
```
としてブラーをかけています。そのため背景がずれたりします。ブラーを強くしてごまかしていますが、ビルドした後に知ったんですけど、`backdrop-filter`というプロパティがあるみたいで。驚いた。Firefoxではつかえないみたいですけど。あるならなんであんなに検索したのに出てこなかったんだよ・・・という感じではあります。。。ということで、こんな感じで修正したい
```css
dock-bar{
  backdrop-filter: blur(30px) brightness(110%);
}
```
ちなみに磨りガラス感を出したいので若干明るくしてます。

# 追加・実装
- [x] 巨大な時計の表示
- [ ] 世界時計とかの実装
- [ ] URLを保存してすぐに飛べるようにする(ブックマーク的な)機能
- [ ] 自動アップデート機能
- [ ] 他のソフトのDLとかアプデ機能

まぁでもこれ作りすぎたら他のソフト作っても・・・ってなるからね。。。テキストエディタとかは別で作りたいね。

注意: これはOSもどきなんかではありません。れっきとしてソフトウェアです。便利なソフトです。ありそうでなかった革命的なソフトです。始まりは2020年3月1日、時計を大きく表示したいと思ったことからです。現在もVer.1.0公開してますけどネットにあったソース丸パクりというかなんというかなんで結構危ないかも。今はサイト参考にして自分でソースコード書いてるよ。

# 追記
最近僕はMonotの開発に力入れてるのでしばらくLitest開発できません。開発再開は11月ごろになる見通しです。

---

*1:  Litest起動時の下にあるバーを出した時のやつ)
